# Generated by Django 5.1.4 on 2024-12-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renderer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poster',
            name='url',
        ),
        migrations.AddField(
            model_name='poster',
            name='director_name',
            field=models.CharField(max_length=126, null=True),
        ),
    ]
