# Generated by Django 5.1.4 on 2024-12-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renderer', '0003_remove_poster_director_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='url',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
