# Generated by Django 5.1.4 on 2024-12-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renderer', '0004_poster_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='description',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='poster',
            name='director_name',
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='poster',
            name='name',
            field=models.CharField(max_length=126, null=True),
        ),
    ]
