# Generated by Django 5.1.4 on 2024-12-22 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renderer', '0005_poster_description_poster_director_name_poster_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='renderer.poster')),
            ],
        ),
    ]
